server:
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/clouddb01
  application:
    name: microservicecloud-dept

#通用mapper的配置
mapper:
  mappers: com.lc.cn.mapper.DeptMapper
  identity: mysql
  not-empty: false

logging:
  level:
    com.lc.cn.mapper : debug
eureka:
  client:
    service-url:
      defaultZone : http://localhost:7001/eureka
  instance:
    instance-id: microservicecloud-dept8001
    prefer-ip-address: true   #访问路径显示IP地址
info:
  app.name: offcn-microservicecloud
  company.name: www.lc.cn
  build.artifactId: $project.artifactId$
  build.version: $project.version$
