server:
  port: 8001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: offcn
    url: jdbc:mysql://localhost:3306/cloudDB01
  application:
    name: microservicecloud-dept

#通用mapper的配置
mapper:
  mappers: com.lc.cn.mapper
  identity: mysql
  not-empty: false

logging:
  level:
    com.lc.cn.mapper : debug
