server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true

#自定义代理名称
# 1.   http://myzuul.com:9527/microservicecloud-dept/dept/get/2
zuul:
  prefix: /lc  #3.  http://myzuul.com:9527/lc/mydept/dept/get/2
  ignored-services: microservicecloud-dept #忽略原真实服务器名 #2 http://localhost:9527/mydept/dept/get/2
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**  #2  http://localhost:9527/mydept/dept/get/2

info:
  app.name: lc-microcloud
  company.name: www.lc.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
